### ISSUE TITLE
Possible DeadLock!

### ISSUE THREAD

**Issue by hafedh-trimeche** [ssnake/DelphiSimpleQueue#1]
Hello,

A DeadLock would be set into try ... finaly block:

 ```
FCS.Enter;
  try
    if Assigned(FCurrentTask) then
      exit;
```
An exit is invoked before FCS.Leave is called. So, if another thread is attempting to put a lock, a DeadLock will be stated.

Best regards.

**Comment by ssnake** [comment]
whole peace of code looks like
```pascal
 FCS.Enter;
  try
    if Assigned(FCurrentTask) then
      exit;
    FCurrentTask := GetNextTask;
    task := FCurrentTask;
    if not Assigned(FCurrentTask) then
      exit;
  finally
    FCS.Leave;
  end;
```
As you can see this blocked is wrapped with try/finally. It means we're sure FCS.Leave is always is called before exit from procedure. Thanks
